# Generated by Django 4.0.1 on 2022-03-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=128)),
                ('videoID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=128)),
                ('videoID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='主题')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='关注度')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128, null=True)),
                ('academy', models.CharField(max_length=128, null=True)),
                ('major', models.CharField(max_length=128, null=True)),
                ('grade', models.CharField(max_length=128, null=True)),
                ('sex', models.CharField(max_length=128, null=True)),
                ('avatar', models.CharField(max_length=128, null=True)),
                ('root', models.BooleanField(default=False, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.IntegerField(primary_key=True, serialize=False)),
                ('academy', models.CharField(max_length=128, verbose_name='学院')),
                ('subject', models.CharField(max_length=128, verbose_name='课程')),
                ('section', models.CharField(max_length=128, verbose_name='章节')),
                ('name', models.CharField(max_length=128, verbose_name='题目')),
                ('content', models.CharField(max_length=128, null=True, verbose_name='内容')),
                ('collect', models.IntegerField(default=0, verbose_name='收藏数')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('file', models.CharField(max_length=128, null=True, verbose_name='文件路径')),
                ('icon', models.CharField(max_length=128, null=True, verbose_name='封面路径')),
                ('owner', models.CharField(max_length=128, null=True, verbose_name='所有者')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='位置')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='videoclasstest1.user', verbose_name='发布者')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.video', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('avatar', models.CharField(blank=True, max_length=64, null=True, verbose_name='头像')),
                ('nickname', models.CharField(default='cumter', max_length=64, verbose_name='昵称')),
                ('tesuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.user', verbose_name='正式用户')),
            ],
        ),
        migrations.CreateModel(
            name='classFavorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.video', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.user', verbose_name='点赞用户')),
            ],
        ),
        migrations.CreateModel(
            name='class_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='以后方便删除', max_length=128, verbose_name='File name')),
                ('cos_path', models.CharField(max_length=128, verbose_name='图片路径')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.video', verbose_name='课程')),
            ],
        ),
    ]
