# Generated by Django 4.0.1 on 2022-03-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('depth', models.PositiveIntegerField(default=1, verbose_name='评论层级')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='赞数')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.video', verbose_name='动态')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='videoclasstest1.commentrecord', verbose_name='回复')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='videoclasstest1.commentrecord', verbose_name='根评')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.user', verbose_name='评论者')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFavorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.commentrecord', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.user', verbose_name='点赞用户')),
            ],
        ),
    ]
