# Generated by Django 4.0.1 on 2022-03-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0002_commentrecord_commentfavorrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrecord',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='videoclasstest1.commentrecord', verbose_name='根评'),
        ),
    ]
