# Generated by Django 4.0.1 on 2022-04-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0004_alter_class_detail_key_newstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='以后方便删除', max_length=128, verbose_name='TencentYun-File name')),
                ('cos_path', models.CharField(max_length=128, verbose_name='图片路径')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.newstest', verbose_name='课程')),
            ],
        ),
    ]
