# Generated by Django 4.0.1 on 2022-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0005_news_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='0f09a137-c518-4993-934b-0f4da807dedd', max_length=64, null=True, verbose_name='用户Token'),
        ),
    ]
