# Generated by Django 4.0.1 on 2022-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0007_alter_class_detail_cos_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_detail',
            name='cos_path',
            field=models.TextField(verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='commentrecord',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2a769641-110b-49dc-8817-87eb4a670450', max_length=64, null=True, verbose_name='用户Token'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
    ]
