# Generated by Django 4.0.1 on 2022-04-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0008_alter_class_detail_cos_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='5d4c3258-2b27-4426-9b00-cfd411028d1b', max_length=64, null=True, verbose_name='用户Token'),
        ),
    ]
