# Generated by Django 4.0.1 on 2022-04-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0009_video_comment_count_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='bb100db0-144b-4544-b95d-a1b527cbe3fb', max_length=64, null=True, verbose_name='用户Token'),
        ),
        migrations.CreateModel(
            name='classcollectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.video', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclasstest1.user', verbose_name='收藏用户')),
            ],
        ),
    ]
