# Generated by Django 4.0.1 on 2022-04-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0010_alter_user_token_classcollectrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='subject',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='0', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2b3d47d5-40bc-4fb3-9357-10386474d76d', max_length=64, null=True, verbose_name='用户Token'),
        ),
    ]
