# Generated by Django 4.0.1 on 2022-04-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0011_remove_video_academy_remove_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstest',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='newstest',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='b86b0b0b-bc9d-428c-b209-950cab4fb192', max_length=64, null=True, verbose_name='用户Token'),
        ),
        migrations.DeleteModel(
            name='news_detail',
        ),
        migrations.DeleteModel(
            name='Newstest',
        ),
    ]
