# Generated by Django 4.0.1 on 2022-04-30 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0012_remove_newstest_topic_remove_newstest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcollectrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='收藏时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classfavorrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='点赞时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='e78924b9-2f23-40dd-ae9e-e56d66510dcb', max_length=64, null=True, verbose_name='用户Token'),
        ),
    ]
