# Generated by Django 4.0.1 on 2022-05-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclasstest1', '0013_classcollectrecord_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cared',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='user',
            name='collected',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='user',
            name='favored',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='ffbb0e53-035b-42d7-9764-73705e17b127', max_length=64, null=True, verbose_name='用户Token'),
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carewho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisbecared', to='videoclasstest1.user', verbose_name='被关注')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carebythis', to='videoclasstest1.user', verbose_name='主人')),
            ],
        ),
    ]
